version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: text-analyzer-app
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - analyzer-network

  nginx:
    image: nginx:1.25-alpine
    container_name: text-analyzer-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
    depends_on:
      - app
    networks:
      - analyzer-network

networks:
  analyzer-network:
    driver: bridge