server:
  version: "v1.0.0"
  port: "8080"

db:
  host: "postgres"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

jwt:
  access_expiry: "60m"
  refresh_expiry: "720h"   


  